### ISSUE TITLE
api->getItem runs into Soap error

### ISSUE THREAD

**Issue by maidzen** [Garethp/php-ews#47] opened 2016-06-20 10:07 UTC
I get a list of E-Mails out of a public Folder
```
$mail = $api->getMailItems($subFolder2->getFolderId());
foreach($mail->items as $message) {
	$mailItem = $api->getItem($message->getItemId());
```

the Code ( $api->getItem ) Triggers on some Mails the following error:
> PHP Fatal error:  Uncaught SoapFault exception: [Client] looks like we got no XML document in /var/www/html/php-ews/src/API/NTLMSoapClient.php:127\nStack trace:\n#0 /var/www/html/php-ews/src/API/NTLMSoapClient.php(127): SoapClient->__call('GetItem', Array)\n#1 /var/www/html/php-ews/src/API/ExchangeWebServices.php(294): garethp\\ews\\API\\NTLMSoapClient->__call('GetItem', Array)\n#2 /var/www/html/php-ews/src/API.php(395): garethp\\ews\\API\\ExchangeWebServices->__call('GetItem', Array)\n#3 /var/www/html/php-ews/src/API.php(395): garethp\\ews\\API\\ExchangeWebServices->GetItem(Array)\n#4 /var/www/html/php-ews/index.php(40): garethp\\ews\\API->getItem(Object(garethp\\ews\\API\\Type\\ItemIdType))\n#5 {main}\n  thrown in /var/www/html/php-ews/src/API/NTLMSoapClient.php on line 127

I have an Mail->item object where the error gets triggered but
ItemID is accessable and it looks the same as on working E-Mails.

I'm new to this API (And EWS) so i don't know which information you need to help me.

Thanks for your help.

**Comment by Garethp** [comment] 2016-06-20 10:36
In `NTLMSoapClient`, can you do a dump on the response that's returned by `__doRequest`, so I can see what the actual request looks like? Also, can you let me know what version you're using? Thanks

**Comment by maidzen** [comment] 2016-06-20 11:06
Hi Garethp,

the xml looks like this
http://pastebin.com/wKJRaNH4

**Comment by Garethp** [comment] 2016-06-20 13:14
By newest, do you mean the latest release (0.8.5) or the `dev-master` branch?

**Comment by maidzen** [comment] 2016-06-20 13:23
dev-master

**Comment by maidzen** [comment] 2016-06-21 08:03
so E-Mails which don't work run into 

1. Soaps __call function 
2. then into Client->endRecord() 
3. then TaskQueue->__construct (Where the error gets thrown)

i don't know why it cant parse some of the e-mails at all there is nothing (at least obvious) special in it
no special chars or stuff like that.

**Comment by Garethp** [comment] 2016-06-21 11:09
Can you try running on `0.8.5`? I don't know if `dev-master` is stable at the moment

**Comment by maidzen** [comment] 2016-06-21 11:12
sure i will downgrade asap and give feedback

**Comment by maidzen** [comment] 2016-06-21 11:39
it produces the same Error

> [Client] looks like we got no XML document in ...

**Comment by Garethp** [comment] 2016-06-21 12:22
Okay, I'll take a look and see if I can reproduce it

**Comment by Garethp** [comment] 2016-06-21 12:27
It might be a BOM issue. In `__doRequest`, can you replace

`return $response->getBody()->__toString();`

with

```php
$xml = (string) $response->getBody();
$xml = preg_replace( '/^(\x00\x00\xFE\xFF|\xFF\xFE\x00\x00|\xFE\xFF|\xFF\xFE|\xEF\xBB\xBF)/', "", $xml);
return $xml;
```

And see if that does anything?

**Comment by maidzen** [comment] 2016-06-21 12:59
hey Gareth, 
unfortunately, no.  i also tried to escape any special chars in the response without success

**Comment by Garethp** [comment] 2016-06-21 13:12
Okay, I'll look in to it further and let you know

**Comment by Garethp** [comment] 2016-06-21 13:42
Okay, if you don't mind I'm going to ask you to do something that I haven't tried for debugging, but that might make things easier. Where you create your API client, can you add these as options for the fourth argument?

```php
'httpPlayback' => [
        'mode' => \garethp\HttpPlayback\Client::RECORD,
        'recordFileName' => 'test.json',
        'recordLocation' => __DIR__
    ]
```

So what I've got when I do it is

```php
$api = API::withUsernameAndPassword("outlook.office365.com", "username", "password", [
    'httpPlayback' => [
    'mode' => 'record',
    'recordFileName' => 'test.json',
    'recordLocation' => __DIR__
]
]);
$api->getServerTimezones();
```

What this should do is create a `test.json` file in the folder of the **file that this code is in**. The `test.json` is just a json serialized array of the results that you're getting. It won't contain any requests, so your username and password will be safe, just the responses from Exchange. If you then upload the file somewhere and send me the link, or email me directly at `blackfireweb@gmail.com`, I can then play back the results that you're getting without actually having to try and get a server environment exactly the same as you. Then I can play around and see what's wrong with the responses and how I can fix it.

**Comment by maidzen** [comment] 2016-06-21 14:07
Hi Garethp,

thanks for your help so far and i would appreciate if you could look ofer my case,
unfortunately no test.json gets generated with the option parameters you gave me.

CHMOD is 777 on the directory, when i debug HttpPlayback class Directory etc. is set correct

i use it like this
```
$api = MailAPI::withUsernameAndPassword('owa.example.de', 'user', 'password, [
    'httpPlayback' => [
		'mode' => 'record',
		'recordFileName' => 'test.json',
		'recordLocation' => __DIR__
	]
]);
```

**Comment by Garethp** [comment] 2016-06-22 12:26
So, looking in the [XML That You Sent Me](http://pastebin.com/wKJRaNH4) on Line 668, you've got this

`<t:ContentType>憼ᕵ坡嫑惻ʚĀ谁䀈刐⋷惹ʔȀ老</t:ContentType>`

And that's where it's failing. It seems to be called `image0.png` on the email with Subject `Angebot_AN22263_Pokini und Zubehöre (R1606269)`. Can you open this email up in your outlook/browser and give me more information on it? What's the image? What's it's actual content type? Also, I think I'll need more info on your server. What's it's location? Is it's language set to something else? It looks like German, right? What kind of encoding do you use for this?

I'm wondering if this can't be fixed by setting encoding settings somewhere, but I need more information first

**Comment by maidzen** [comment] 2016-06-22 13:31
Hi Gareth,
Content Type should be Image/PNG but i cant find a way in outlook to show me the content Type of an attachment in an email of an public folder (...) 

The Server is encoding in Unicode. The Language is German. Location LAN (so no external Webserver or Something)

**Comment by maidzen** [comment] 2016-06-22 14:15
Hey Gareth, i preg_replaced the content Type in doRequest and it works !!!! thank you so much!

**Comment by Garethp** [comment] 2016-06-22 14:17
I'll look in to stripping bad characters from XML for the next release

**Closed** 2016-06-23 09:04 UTC
